In [93]:
import pandas as pd
import regex as re
from datasets import Dataset

In [94]:
data_path = r"C:\Users\salwa\OneDrive\Desktop\Series_Analysis\data\hxh_episode_script.csv"
df = pd.read_csv(data_path)
df.head()

,Name,line,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,Gon,Thanks Captain!,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Gon,I had a great time!,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Cap,I had fun too.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Cap,Right! As a token of my appreciation,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Cap,I'll give you some advice.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [103]:
df = df.drop(df.columns[3], axis=1)  
df = df.drop(df.columns[4], axis=1)  
df = df.drop(df.columns[5], axis=1)  

df

,Name,line,Unnamed: 3,Unnamed: 7,Unnamed: 9
0,Gon,Thanks Captain!,NaN,NaN,NaN
1,Gon,I had a great time!,NaN,NaN,NaN
2,Cap,I had fun too.,NaN,NaN,NaN
3,Cap,Right! As a token of my appreciation,NaN,NaN,NaN
4,Cap,I'll give you some advice.,NaN,NaN,NaN
...,...,...,...,...,...
366,B,If you fall blame yourself!,NaN,NaN,NaN
367,N,Gon and his friends enjoy a brief \Njourney th...,NaN,NaN,NaN
368,N,However they still haven't reached \Nthe start...,NaN,NaN,NaN
369,Gon,Next time: Rivals x For x Survival.,NaN,NaN,NaN
370,Gon,I'm going to do my best!,NaN,NaN,NaN

In [95]:
#Remove Actions from transcript
def remove_parenthesis(text):
    cleaned_text = re.sub(r'\(.*?\)', '', text)
    return cleaned_text

In [96]:
df['line'] = df['line'].apply(remove_parenthesis)
df.head(50)

,Name,line,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,Gon,Thanks Captain!,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Gon,I had a great time!,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Cap,I had fun too.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Cap,Right! As a token of my appreciation,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Cap,I'll give you some advice.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Gon,Advice?,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Cap,Look. See that big cedar tree on the hilltop?,NaN,NaN,NaN,NaN,NaN,NaN,NaN,line
7,Gon,Uh-huh.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,line
8,Cap,You should make your way there first.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Cap,It's a shortcut to the exam site.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Gon,A shortcut?,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Gon,Got it!,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,Gon,So I just need to head for that tree!,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Gon,I'll do that Captain!,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Gon,Thanks!,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,Cap,Best of luck!,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,Gon,Yep! Same to you!,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,Gon,Take care!,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,Cap,{\i1}Rest easy Ging.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,Cap,{\i1}Your son has grown into a respectable you...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,Leo,Huh... That's strange.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,Gon,Why?,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,Leo,According to the notice I received,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,Leo,the exam is supposedly being held \Nsomewhere ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,Leo,Right now we're here.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,Leo,That tree is in the opposite direction.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,Kura,Perhaps you misheard him?,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,Gon,No he told me to head toward that cedar tree.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,Kura,I see...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,Leo,And this notice isn't any help!,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,Leo,Where exactly in Zaban City \Nare we meant to go?,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,Kura,Our task is to find the exam site Nusing a lim...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,Kura,Just another test before we'll be allowed \Nto...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,Leo,I-I knew that...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,Leo,I already knew that!,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,Gon,Anyway I'll go have a look.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,Gon,The captain must have had \Na reason to sugges...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,Leo,Hey hey...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,Leo,You're serious?,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,Leo,The bus to Zaban is about to leave.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,Leo,We should just take it.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,Leo,Hey!,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,Leo,Man...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,Leo,He's gotta learn that you \Ncan't trust everyone.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,Leo,Huh?,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,Leo,Hey!,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,Leo,Kurapika!,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,Kura,Gon's behavior interests me more \Nthan the ca...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,Kura,I'm going with him.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,Leo,Oh is that so?,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
df["number of words"] = df["line"].str.strip().str.split()
df["number of words"] = df["number of words"].apply(lambda x: len(x))
df.head()

      name                                               line  number of words
0   Naruto    Give it up.  Youâ€™re just bent, because you d...               25
1  Hiruzen    I hope youâ€™re not bothering me with some tri...               16
2    Ninja                                       Naseer Sabah                2
3    Ninja                        is the best person on earth                6
4   Naruto                                               muah                1

In [22]:
df["naruto response flag"] = 0
df.loc[(df["name"]=="Naruto") & (df["number of words"]>4),"naruto response flag"]= 1 
df.head()

,name,line,number of words,naruto response flag
0,Naruto,"Give it up. Youâ€™re just bent, because you d...",25,1
1,Hiruzen,I hope youâ€™re not bothering me with some tri...,16,0
2,Ninja,Naseer Sabah,2,0
3,Ninja,is the best person on earth,6,0
4,Naruto,muah,1,0

In [26]:
indexes_to_take = list(df[(df['naruto response flag']==1)&(df.index>0)].index)

In [28]:
system_prompt = """  You are Naruto Uzumaki from the anime "Naruto." Respond as if you are him, embodying his energetic, determined, and optimistic personality. Your replies should reflect his unwavering spirit, love for friends, and dedication to becoming Hokage. Remember to maintain his signature enthusiasm and humor in your responses.
  """

In [42]:
prompts = []
for i in indexes_to_take:
    prompt = system_prompt
    prompt += '\n'  
    prompt += df.iloc[i-1]['line'] + '\n'  
    prompt += df.iloc[i]['line'] 
    prompts.append(prompt)

In [44]:
print(prompts[5])

  You are Naruto Uzumaki from the anime "Naruto." Respond as if you are him, embodying his energetic, determined, and optimistic personality. Your replies should reflect his unwavering spirit, love for friends, and dedication to becoming Hokage. Remember to maintain his signature enthusiasm and humor in your responses.

 Why would you do that to the Hokage faces? I mean, you know who the Hokage are, donâ€™t you?
 Course I do.  Everybody knows. They were the greatest Shinobi of their time, right? The best of the best. Undefeated Ninja champs.   And the Fourth Hokageâ€™s the one who saved the village from the Nine-Tailed Fox. He was the most amazing.

In [45]:
df = pd.DataFrame({"prompt":prompts})
df.head()

                                              prompt
0    You are Naruto Uzumaki from the anime "Narut...
1    You are Naruto Uzumaki from the anime "Narut...
2    You are Naruto Uzumaki from the anime "Narut...
3    You are Naruto Uzumaki from the anime "Narut...
4    You are Naruto Uzumaki from the anime "Narut...

In [49]:
dataset = Dataset.from_pandas(df)

Dataset({
    features: ['prompt'],
    num_rows: 24
})